//
//  Sample_Gallery.swift
//  IN SOPT KakaoTalk
//
//  Created by 장석우 on 2022/10/25.
//

import UIKit
extension Sample{
    static let galleryData = [
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.swissHotel),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.swissHotel),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.swissHotel),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.swissHotel),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.swissHotel),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.swissHotel),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.swissHotel),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.swissHotel),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.swissHotel),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.swissHotel),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.swissHotel),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.swissHotel),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.myProfile),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.swissHotel),
                                UIImage(named: Image.hamburgerProfile),
                                UIImage(named: Image.swissHotel)
                            ]
}
