//
//  Sample_Chat.swift
//  IN SOPT KakaoTalk
//
//  Created by 장석우 on 2022/10/25.
//

import UIKit

extension Sample{
    static let chatData = [
                            ChatModel(profileImage: UIImage(named: Image.myProfile),
                                      name: "iOS 공지방",
                                      recentMessage: "[3차 보충세미나 및 세미나 자료 형식 수요조사]",
                                      recentMessageTime: "어제",
                                      numbersOfNotReadMessage: 12),
                            ChatModel(profileImage: UIImage(named: Image.defaultProfile),
                                      name: "iOS 공지방",
                                      recentMessage: "[3차 보충세미나 및 세미나 자료 형식 수요조사]\n만약두줄이라면?",
                                      recentMessageTime: "어제",
                                      numbersOfNotReadMessage: 12),
                            ChatModel(profileImage: UIImage(named: Image.defaultProfile),
                                      name: "iOS 공지방",
                                      recentMessage: "[3차 보충세미나 및 세미나 자료 형식 수요조사]\n세줄이면\n 어케될까",
                                      recentMessageTime: "어제",
                                      numbersOfNotReadMessage: 12),
                            ChatModel(profileImage: UIImage(named: Image.defaultProfile),
                                      name: "iOS 공지방",
                                      recentMessage: "[3차 보충세미나 및 세미나 자료 형식 수요조사]",
                                      recentMessageTime: "어제",
                                      numbersOfNotReadMessage: 12),
                            ChatModel(profileImage: UIImage(named: Image.defaultProfile),
                                      name: "iOS 공지방",
                                      recentMessage: "[3차 보충세미나 및 세미나 자료 형식 수요조사]",
                                      recentMessageTime: "어제",
                                      numbersOfNotReadMessage: 12),
                            ChatModel(profileImage: UIImage(named: Image.defaultProfile),
                                      name: "iOS 공지방",
                                      recentMessage: "[3차 보충세미나 및 세미나 자료 형식 수요조사]",
                                      recentMessageTime: "어제",
                                      numbersOfNotReadMessage: 12),
                            ChatModel(profileImage: UIImage(named: Image.defaultProfile),
                                      name: "iOS 공지방",
                                      recentMessage: "[3차 보충세미나 및 세미나 자료 형식 수요조사]\n만약두줄이라면?",
                                      recentMessageTime: "어제",
                                      numbersOfNotReadMessage: 12),
                            ChatModel(profileImage: UIImage(named: Image.defaultProfile),
                                      name: "iOS 공지방",
                                      recentMessage: "[3차 보충세미나 및 세미나 자료 형식 수요조사]\n세줄이면\n 어케될까",
                                      recentMessageTime: "어제",
                                      numbersOfNotReadMessage: 12),
                            ChatModel(profileImage: UIImage(named: Image.defaultProfile),
                                      name: "iOS 공지방",
                                      recentMessage: "[3차 보충세미나 및 세미나 자료 형식 수요조사]",
                                      recentMessageTime: "어제",
                                      numbersOfNotReadMessage: 12),
                            ChatModel(profileImage: UIImage(named: Image.defaultProfile),
                                      name: "iOS 공지방",
                                      recentMessage: "[3차 보충세미나 및 세미나 자료 형식 수요조사]",
                                      recentMessageTime: "어제",
                                      numbersOfNotReadMessage: 12),
                            ChatModel(profileImage: UIImage(named: Image.defaultProfile),
                                      name: "iOS 공지방",
                                      recentMessage: "[3차 보충세미나 및 세미나 자료 형식 수요조사]",
                                      recentMessageTime: "어제",
                                      numbersOfNotReadMessage: 12),
                            ChatModel(profileImage: UIImage(named: Image.defaultProfile),
                                      name: "iOS 공지방",
                                      recentMessage: "[3차 보충세미나 및 세미나 자료 형식 수요조사]\n만약두줄이라면?",
                                      recentMessageTime: "어제",
                                      numbersOfNotReadMessage: 12),
                            ChatModel(profileImage: UIImage(named: Image.defaultProfile),
                                      name: "iOS 공지방",
                                      recentMessage: "[3차 보충세미나 및 세미나 자료 형식 수요조사]\n세줄이면\n 어케될까",
                                      recentMessageTime: "어제",
                                      numbersOfNotReadMessage: 12),
                            ChatModel(profileImage: UIImage(named: Image.defaultProfile),
                                      name: "iOS 공지방",
                                      recentMessage: "[3차 보충세미나 및 세미나 자료 형식 수요조사]",
                                      recentMessageTime: "어제",
                                      numbersOfNotReadMessage: 12),
                            ChatModel(profileImage: UIImage(named: Image.defaultProfile),
                                      name: "iOS 공지방",
                                      recentMessage: "[3차 보충세미나 및 세미나 자료 형식 수요조사]",
                                      recentMessageTime: "어제",
                                      numbersOfNotReadMessage: 12),
                            
    ]
}
